# Generated by Django 2.2 on 2019-06-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('apartment_number', models.CharField(blank=True, max_length=10)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('sent', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('tracking_number', models.CharField(max_length=200)),
                ('books', models.ManyToManyField(related_name='orders', to='books.Book')),
                ('dnd_pages', models.ManyToManyField(related_name='orders', to='books.DNDPage')),
            ],
        ),
    ]
